// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("")]
    public partial class Feature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Login.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pl-PL"), "", "Jako użytkownik aplikacji mobilnej \nchcę ekran logowania \naby mieć możliwość zapi" +
                    "sywania swoich postępów", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Prawidłowe logowanie do aplikacji")]
        public virtual void PrawidloweLogowanieDoAplikacji()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Prawidłowe logowanie do aplikacji", ((string[])(null)));
#line 8
this.ScenarioSetup(scenarioInfo);
#line 9
 testRunner.Given("aktywne konto google", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Mając ");
#line 10
 testRunner.When("na ekranie logowania podam swój login i hasło", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Jeśli ");
#line 11
 testRunner.And("zatwierdze dane odpowiednim przyciskiem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "I ");
#line 12
 testRunner.Then("będę miał dostęp do wszystkich funkcjonalności aplikacji", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Wtedy ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Nieprawidłowe logowanie do aplikacji")]
        public virtual void NieprawidloweLogowanieDoAplikacji()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Nieprawidłowe logowanie do aplikacji", ((string[])(null)));
#line 14
this.ScenarioSetup(scenarioInfo);
#line 15
 testRunner.Given("brak konta google", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Mając ");
#line 16
 testRunner.When("na ekranie logowania podam nieistniejący login i hasło", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Jeśli ");
#line 17
 testRunner.And("zatwierdze dane odpowiednim przyciskiem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "I ");
#line 18
 testRunner.Then("nie będę miał dostępu do żadnej funkcjonalności aplikacji", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Wtedy ");
#line 19
 testRunner.And("zostanę przeniesiony na ekran mówiący o nieudanej próbie logowania", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "I ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
