// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("KontrolowanieWagi")]
    public partial class KontrolowanieWagiFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "MeasureWeight.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pl"), "KontrolowanieWagi", "\tJako użytkownik aplikacji mobilnej \r\n\tchcę korzystać z formularza rejestracji wa" +
                    "gi\r\n\taby śledzić jak zmienia się moja waga podczas treningu", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Wprowadyenie aktualnej wagi")]
        public virtual void WprowadyenieAktualnejWagi()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Wprowadyenie aktualnej wagi", ((string[])(null)));
#line 8
this.ScenarioSetup(scenarioInfo);
#line 9
 testRunner.Given("uruchomioną aplikację Perfect Life", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Mając ");
#line 10
 testRunner.When("zaloguję się za pomocą prawidłowych danych", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Jeśli ");
#line 11
 testRunner.Then("zobaczę ekran z polem umożliwiającym wprowadzenie mojej aktualnej wagi", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Wtedy ");
#line 12
 testRunner.When("wprowadzę moją wagę", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Jeśli ");
#line 13
 testRunner.And("zatwierdzę swój wybór przyciskiem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "I ");
#line 14
 testRunner.Then("wartość wagi zostanie zostana wysłana i zapisana na serwerze", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Wtedy ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Wyświetlenie wykresu obrazującego zmianę mojej wagi w czasie")]
        public virtual void WyswietlenieWykresuObrazujacegoZmianeMojejWagiWCzasie()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Wyświetlenie wykresu obrazującego zmianę mojej wagi w czasie", ((string[])(null)));
#line 16
this.ScenarioSetup(scenarioInfo);
#line 17
 testRunner.Given("wprowadzoną wartość wagi z kilku ostatnich dni", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Mając ");
#line 18
 testRunner.When("zaloguję się do aplikacji", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Jeśli ");
#line 19
 testRunner.And("wybiorę opcję śledzenia postępów", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "I ");
#line 20
 testRunner.Then("zobaczę wykres słupkowy prezentujący moje postępy", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Wtedy ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
